# Generated by Django 5.1.6 on 2025-02-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_ibento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
