# Generated by Django 3.2 on 2025-03-03 00:44

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
