# Generated by Django 3.2 on 2025-03-31 04:02

import api.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasPerfil',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, max_length=50, primary_key=True, serialize=False)),
                ('categoria_perfil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('preferencias_evento', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('save_events', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('favourite_events', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('profile_pic', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('preferencias_generales', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('is_ine_validated', models.BooleanField(default=False)),
                ('is_validated_camera', models.BooleanField(default=False)),
                ('matches', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('futuros_matches', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('blocked', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoriaPerfil',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, max_length=50, primary_key=True, serialize=False)),
                ('nombre_subcategoria_perfil', models.CharField(max_length=70)),
                ('categoria_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias_perfiles', to='api.categoriasperfil')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, max_length=50, primary_key=True, serialize=False)),
                ('nombre_subcategoria', models.CharField(max_length=70)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='api.categoriaevento')),
            ],
        ),
    ]
