# Generated by Django 3.2 on 2025-03-24 06:31

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasPerfil',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, max_length=50, primary_key=True, serialize=False)),
                ('categoria_perfil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoriaPerfil',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, max_length=50, primary_key=True, serialize=False)),
                ('nombre_subcategoria_perfil', models.CharField(max_length=70)),
                ('categoria_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias_perfiles', to='api.categoriasperfil')),
            ],
        ),
    ]
