# Generated by Django 3.2.21 on 2025-02-27 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
