# Generated by Django 3.2 on 2025-05-08 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='futuros_matches',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='matches',
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interaccion', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('fecha_interaccion', models.DateTimeField(auto_now_add=True)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_destino', to=settings.AUTH_USER_MODEL)),
                ('usuario_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_origen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario_origen', 'usuario_destino')},
            },
        ),
    ]
