# Generated by Django 3.2 on 2025-04-03 06:43

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_fcm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, max_length=50, primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='api.conversacion')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='api.usuario')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, max_length=50, primary_key=True, serialize=False)),
                ('fecha_match', models.DateTimeField(auto_now_add=True)),
                ('usuario_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_a', to='api.usuario')),
                ('usuario_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_b', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='conversacion',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='api.matches'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='usuario_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_a', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='usuario_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_b', to='api.usuario'),
        ),
    ]
