# Generated by Django 3.2 on 2025-05-19 17:32

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='buscar_match',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token_fcm',
        ),
        migrations.AddField(
            model_name='usuario',
            name='eventos_buscar_match',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tokens_fcm',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
