# Generated by Django 3.2 on 2025-05-21 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250519_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('usuario_bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_bloqueador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario_bloqueador', 'usuario_bloqueado')},
            },
        ),
    ]
