# Generated by Django 3.2 on 2025-04-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250403_0043'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matches',
            constraint=models.UniqueConstraint(fields=('usuario_a', 'usuario_b'), name='unique_match_pair'),
        ),
    ]
