# Generated by Django 3.2 on 2025-05-09 06:06

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250507_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='assistants',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
