# Generated by Django 3.2 on 2025-05-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_evento_assistants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEventoMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=100)),
                ('evento_id', models.CharField(max_length=100)),
                ('buscar_match', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='modo_busqueda_match',
            field=models.CharField(choices=[('global', 'Global'), ('evento', 'Por evento')], default='global', max_length=20),
        ),
    ]
