# Generated by Django 3.2 on 2025-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_matches_unique_match_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='preferencias_completadas',
            field=models.BooleanField(default=False),
        ),
    ]
