# Generated by Django 3.2 on 2025-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250513_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionEventoMatch',
        ),
        migrations.AddField(
            model_name='evento',
            name='buscar_match',
            field=models.BooleanField(default=False),
        ),
    ]
