# Generated by Django 3.2 on 2025-06-12 08:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fcmtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metricas',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('num_ine_checked', models.IntegerField(default=0)),
                ('num_ine_validated', models.IntegerField(default=0)),
                ('num_face_checked', models.IntegerField(default=0)),
                ('num_face_validated', models.IntegerField(default=0)),
                ('num_matches', models.IntegerField(default=0)),
                ('num_interactions', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'metricas',
            },
        ),
    ]
