# Generated by Django 3.2 on 2025-06-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_matches_compatibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='compatibilidad',
            field=models.FloatField(default=0.0),
        ),
    ]
