# Generated by Django 3.2 on 2025-04-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20250423_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_reset_password',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_reset_password_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
