# Generated by Django 3.2 on 2025-04-24 20:21

import api.models
from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20250423_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('cost', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('location', models.CharField(max_length=100)),
                ('coordenates', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('classifications', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('dates', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('imgs', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
