# Generated by Django 3.2 on 2025-04-27 09:15

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20250427_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('_id', models.CharField(default=api.models.generate_objectid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('price', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('location', models.CharField(max_length=100)),
                ('coordenates', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('classifications', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('dates', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('imgs', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('url', models.CharField(default='', max_length=100)),
                ('numLike', models.IntegerField(default=0)),
                ('numSaves', models.IntegerField(default=0)),
            ],
        ),
    ]
